 /*
           Programmer Name: Bhargav Sai Krishna, Ravuri
           Problem Identification: MACRO Assignment 8 Problem 16
           Date:4/3/2015
           Purpose:  To use macros that will display the product name and product category for products produced in a specific country

 */

  * The libname statement is used to refer to the directory where the ORION database is located;
  libname orion  '/Network/Servers/mozart.stat.wvu.edu/bayes/abilling/public_html/STAT522/SQL/DATA'; /* Windows and UNIX */
  *libname orion  '.WORKSHOP.SASDATA'; /* zOS mainframe*/

* Macro parameters list contains a marco variable that can be used within the macro;
* macros with positional  parameters use one to one correspondence between parameter name on macro definition and parameter value on mac
ro call;
* Macro enables to write macro programs;
* mprint option writes to SAS log the text that is generated by macro execution;
* symbolgen option is used to display the results of resolved macro variable reference in the SAS log;
* A Macro call is not a statement so semicolon is not required;
* Order by clause is used to sort query results in specific order by default the values in the specified column are sorted in ascending
order. the order by clasue contains numbers representing the position of an item in the SELECT clause;


options mprint symbolgen;

%macro products(country);


proc sql;
title " Products Produced in &country ";
select  Product_Category,Product_Name from orion.product_dim where Supplier_Country="&country" order by 1,2;
quit;

%mend products;





%products(CA)
%products(AU)
