 /*
           Programmer Name: Bhargav Sai Krishna, Ravuri
           Problem Identification: MACRO Assignment 7 Problem 13
           Date:3/21/2015
           Purpose:  To use macros with keyword parameters and print the all the sales of a particular product category

 */

  * The libname statement is used to refer to the directory where the ORION database is located;
  libname orion  '/Network/Servers/mozart.stat.wvu.edu/bayes/abilling/public_html/STAT522/SQL/DATA'; /* Windows and UNIX */
  *libname orion  '.WORKSHOP.SASDATA'; /* zOS mainframe*/

* Macro parameters list contains a marco variable that can be used within the macro;
* macros with keyword parameters include default value for the parameters after equal(=) sign;
* Macro enables to write macro programs;
* mprint option writes to SAS log the text that is generated by macro execution;
* symbolgen option is used to display the results of resolved macro variable reference in the SAS log;
* A Macro call is not a statement so semicolon is not required;
* noncorrelated subquery is query with in another query and "any" is used so that the comparision is true if it is true for any of
the values that subquery returns;
* summary function sum() calculates the sum of Total retail prices across rows;
options mprint symbolgen;

%macro sales(prod_categ=Clothes,start_date=01JAN03,end_date=31DEC03);


proc sql;
title "The sales for &prod_categ between &start_date and &end_date";
select sum(total_retail_price)  'Sales' from orion.order_fact where product_id=any(select product_id from
orion.product_dim where product_category="&prod_categ") and Order_Date between "&start_date"d and "&end_date"d;
quit;

%mend sales;





%sales(prod_categ=Swim Sports,start_date=01MAR04,end_date=31DEC05)
%sales(prod_categ=Shoes,end_date=31DEC05)
