 /*
           Programmer Name: Bhargav Sai Krishna, Ravuri
           Problem Identification: MACRO Assignment 9 Problem 17
           Date:4/8/2015
           Purpose:To use macros that will display the name and termination date of employees who were terminated after a specific date

 */

  * The libname statement is used to refer to the directory where the ORION database is located;
  libname orion  '/Network/Servers/mozart.stat.wvu.edu/bayes/abilling/public_html/STAT522/SQL/DATA'; /* Windows and UNIX */
  *libname orion  '.WORKSHOP.SASDATA'; /* zOS mainframe*/

* Macro parameters list contains a marco variable that can be used within the macro;
* macros with positional  parameters use one to one correspondence between parameter name on macro definition and parameter value on mac
ro call;
* Macro enables to write macro programs;
* mprint option writes to SAS log the text that is generated by macro execution;
* symbolgen option is used to display the results of resolved macro variable reference in the SAS log;
* A Macro call is not a statement so semicolon is not required;
* Order by clause is used to sort query results in specific order by default the values in the specified column are sorted in ascending
order. the order by clasue contains numbers representing the position of an item in the SELECT clause;
* A query that lists multiple tables in from clause without a where clause produces all possible combinations of rows from all tables. t
his result is called cartesian product;
* Inner join resembles a subset of cartesian product. On clause specifes the join criteria. where clause is used to subset the results;
* SAS formats can be used to customize PROC SQL output, the format= column modifier is used to alter the appearance of the values in tha
t column;


 options mprint symbolgen;


%macro termination(date);


proc sql;
title "Employees terminated after &date ";
select  employee_name,employee_term_date format=mmddyy10. from orion.employee_payroll p inner join orion.employee_addresses a on
  p.employee_id=a.employee_id where employee_term_date>"&date"d order by 1;

quit;

%mend termination;





%termination(01jan2005)
%termination(25dec2006)
